import type { Metadata } from "next";
import "./globals.css";
import { ClientProviders } from "../src/shared/providers/client-providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          <SessionGate>{children}</SessionGate>
        </ClientProviders>
      </body>
    </html>
  );
}

function SessionGate({ children }: { children: React.ReactNode }) {
  // Minimal gate — no redirect guard; just a simple example placeholder
  // This can later be replaced by feature-level protection
  return <>{children}</>;
}
